version: '3'
services:
  firefox:
    image: jlesage/firefox:v23.11.3
    container_name: firefox
    shm_size: 1g
    ports:
      - "5800:5800"
      - "5900:5900"
    environment:
      - TZ=Asia/Hong_Kong
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - KEEP_APP_RUNNING=1
      - ENABLE_CJK_FONT=1
      - VNC_PASSWORD=ML2HZmfGKq6eiT
    volumes:
      - "/docker/appdata/firefox:/config:rw"